name: learn-github-actions
run-name: ${{ github.ref }} - ${{ github.actor }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Author
      - run: echo ${{ github.actor }}
