name: Deploy Blazor WebAssembly App to GitHub Pages
run-name: ${{ github.actor }} made push request on ${{ github.ref }}

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: .NET 
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - run: Building Signify Web App
        working-directory: Signify.Web

      - name: Restore dependencies
        run: dotnet restore
        working-directory: Signify.Web

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: Signify.Web

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ../release
        working-directory: Signify.Web

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./release/wwwroot