name: learn-github-actions
run-name: ${{ github.actor }} made push request on ${{ github.ref }}

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: Signify.Web/global.json
      - run: Building Signify Website
        working-directory: Signify.Web
