name: learn-github-actions
run-name: Author - ${{ github.actor }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: Branch ${{ github.ref }}
